name: Contribution checks
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  stable:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: "check"
            python: "3.9"
            os: "ubuntu-latest"
          - name: "py37 (ubuntu)"
            python: "3.7"
            python_arch: "x64"
            os: "ubuntu-latest"
          - name: "py37 (windows)"
            python: "3.7"
            python_arch: "x64"
            os: "windows-latest"
          - name: "py37 (macos)"
            python: "3.7"
            python_arch: "x64"
            os: "macos-latest"
          - name: "py38 (ubuntu)"
            python: "3.8"
            python_arch: "x64"
            os: "ubuntu-latest"
          - name: "py38 (windows)"
            python: "3.8"
            python_arch: "x64"
            os: "windows-latest"
          - name: "py38 (macos)"
            python: "3.8"
            python_arch: "x64"
            os: "macos-latest"
          - name: "py39 (ubuntu)"
            python: "3.9"
            python_arch: "x64"
            os: "ubuntu-latest"
          - name: "py39 (windows)"
            python: "3.9"
            python_arch: "x64"
            os: "windows-latest"
          - name: "py39 (macos)"
            python: "3.9"
            python_arch: "x64"
            os: "macos-latest"
          - name: "py310 (ubuntu)"
            python: "3.10"
            python_arch: "x64"
            os: "ubuntu-latest"
          - name: "py310 (windows)"
            python: "3.10"
            python_arch: "x64"
            os: "windows-latest"
          - name: "py310 (macos)"
            python: "3.10"
            python_arch: "x64"
            os: "macos-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.python_arch }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Check EddyMotion
        run: python -m flake8 src
